name: location_services
description: Determine if location services status
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: asia.ivity.flutter.location_services
    pluginClass: LocationServicesPlugin
